name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:win

      - name: Electron Builder
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.RHYTHMIX_TOKEN }}
